### ISSUE TITLE
Could you provide this as a pypi wheel?

### ISSUE THREAD

**Issue by jovany-wang** [lluissm/license-header-checker#50]
So that, I can `pip install license-header-checker` as an official version.

**Comment by lluissm** [comment]
Hi @jovany-wang ,

Thank you for writing.

Have you tried using the install script as explained in the readme? It is just one line and it will download a binary for your platform. Isn't that more convenient?

`curl -s https://raw.githubusercontent.com/lluissm/license-header-checker/master/install.sh | bash`

**Comment by jovany-wang** [comment]
Yes, it works.

But I'm concerning about that it's not a released file. For example, `master/install.sh` will be changed tomorrow.
