### ISSUE TITLE
[Suggestion] Regexp-based header detection

### ISSUE THREAD

**Issue by eutro** [lluissm/license-header-checker#51]
I'd like to suggest using a (customizable) regular expression instead of a hand-rolled parser for header comments. This would allow for different comment styles, not just `/* ... */`. The default regular expression could also be changed to support a wider array of delimiters.

I've implemented it for my own uses in my fork in a commit here https://github.com/eutro/license-header-checker/commit/63da1fa1a8fa4f135c51389f62e579a6613e4a7b, please feel free to cherry-pick it, though I'm not enough of a Go expert to be sure I've done things properly (the tests pass, at least, and it works for my uses). The README would also need an update.

**Comment by lluissm** [comment]
Hi @eutro,

Sorry for the late reply, I somehow missed your message. 

Thank you for the suggestion and sample code, it is indeed an interesting addition. 

I have started working on it here: https://github.com/lluissm/license-header-checker/pull/53

**Comment by lluissm** [comment]
Closing this issue as the feature has been released in https://github.com/lluissm/license-header-checker/releases/tag/v1.5.0

Thank you again for the suggestion :)
